name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        # Add your build steps here
        echo "Building the project..."
    - name: Test
      run: |
        # Add your test steps here
        echo "Running tests..."
    - name: Deploy
      run: |
        # Add your deployment steps here
        echo "Deploying the application..."