name: CI/CD Pipeline

# Trigger the workflow on push and pull_request events
on:
  push:  # Runs on code push
    branches:
      - main  # Specify the branch to trigger on
  pull_request:  # Runs on pull request creation
    branches:
      - main  # Specify the branch to trigger on
  schedule:  # Schedule the workflow to run nightly
    - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          pip install pytest flake8  # Install pytest and flake8

      - name: Run flake8
        run: |
          flake8 .  # Run flake8 for code quality checks

      - name: Run pytest
        run: |
          pytest  # Run pytest for testing
